name: Build and Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: build
      run: dotnet build -c Release src/Dahomey.Json
    - name: test
      run: dotnet test -c Release src/Dahomey.Json.Tests
