name: Build and Test

on:
  push:    
    paths:
      - 'src/**'
      - '.github/workflows/**'
    branches:
      - '**'
    tags-ignore:
      - '*.*.*'
  pull_request:    
    paths:
      - 'src/**'
      - '.github/workflows/**'
    branches:
      - '**'
    tags-ignore:
      - '*.*.*'       

jobs:
  build_and_test:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        dummy: [0]
        include:
          - sdk: '3.1.100'
            lib_framework: 'netcoreapp3.1'
            test_framework: 'netcoreapp3.1'
          - sdk: '3.1.100'
            lib_framework: 'netcoreapp3.0'
            test_framework: 'netcoreapp3.0'
          - sdk: '2.2.207'
            lib_framework: 'netstandard2.0'
            test_framework: 'netcoreapp2.2'
          - sdk: '2.2.207'
            lib_framework: 'netstandard2.0'
            test_framework: 'netcoreapp2.1'
        
    name: sdk ${{ matrix.sdk }} lib ${{matrix.lib_framework}} test ${{matrix.test_framework}}

    steps:
    - name: checkout
      uses: actions/checkout@v1

    - name: setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.sdk }}
    
    - name: build
      run: dotnet build -c Release -f ${{matrix.lib_framework}} src/Dahomey.Json
    
    - name: test
      run: dotnet test -c Release -f ${{matrix.test_framework}} src/Dahomey.Json.Tests
