name: Build and Test

on:
  push:    
    paths:
      - 'src/**'
      - '.github/workflows/**'
    branches:
      - '**'
    tags-ignore:
      - '*.*.*'
  pull_request:    
    paths:
      - 'src/**'
      - '.github/workflows/**'
    branches:
      - '**'
    tags-ignore:
      - '*.*.*'       

jobs:
  build_and_test:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        dotnet: [ '2.2.207', '3.0.100', '3.1.100' ]
        
    name: .net ${{ matrix.dotnet }}

    steps:
    - name: checkout
      uses: actions/checkout@v1

    - name: setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    
    - name: build
      run: dotnet build -c Release src/Dahomey.Json
    
    - name: test
      run: dotnet test -c Release src/Dahomey.Json.Tests
